baseURL = "https://yanlinlin.cn/ARTS-Weekly-BioMed/"
title = "颜林林的“生物医学ARTS”打卡记录"
theme = "simple-style"
paginate = 20
googleAnalytics = "UA-74397492-1"
copyright = "2019-2020 Linlin Yan. [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/deed.zh) | [京ICP备18031542号-1](http://www.beian.miit.gov.cn/)"

[markup.goldmark.renderer]
unsafe = true

[params]
githubURL = "https://github.com/yanlinlin82/ARTS-Weekly-BioMed/"

[markup.highlight]
codeFences = true
lineNos = true
style = "monokailight"

[permalinks]
post = "/:slug/"
page = "/:slug/"

[[menu.main]]
weight = 10
name = "目录"
url = "/"

[[menu.main]]
weight = 20
name = "算法(A)"
url = "/algorithm/"

[[menu.main]]
weight = 30
name = "资源(R)"
url = "/resource/"

[[menu.main]]
weight = 40
name = "技术(T)"
url = "/technology/"

[[menu.main]]
weight = 50
name = "统计(S)"
url = "/statistics/"

[[menu.main]]
weight = 90
name = "关于"
url = "/about/"

[[menu.parent]]
name = ">>个人网站"
url = "http://yanlinlin.cn/"
